### ISSUE TITLE
images are not showing in photos fragment 

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#108]
identify why is this happening and solve the bug

**Comment by SB2318** [comment]
I want to work on this issue under JWOC . Assign it to me.

**Comment by vivekgupta4Git** [comment]
This issue is similar to issue #109

**Comment by SB2318** [comment]
@vivekgupta4Git  please check again, then say something. Because I will discuss about my issue with my mentor before I start my work.
At that time you can clear your doubt.

**Comment by vivekgupta4Git** [comment]
I have no doubt, this issue is created bcoz I missed one line from last pr so i am just notifying.

**Comment by SB2318** [comment]
Please wait, I already study the project. And the problem is different from yours thought.

**Comment by SB2318** [comment]
However, if you still think  in this way, then I suggest you please correct your mistake and again create another PR.
I think, this is much better.

**Comment by vivekgupta4Git** [comment]
alright. If you need hint check my pr for #110. 
Its good you study!! :)

**Comment by SB2318** [comment]
See it carefully, I have to solve this problem.

https://user-images.githubusercontent.com/87614560/155082678-262a98d5-cd18-4f8b-b832-b41fcea18f82.mp4

If your code solve this, I will remove my assignment. Other wise your PR definitely helps me.

**Comment by DarkFalc0n** [comment]
I want to work on this Issue Under JWOC
