### ISSUE TITLE
Modify Readme File 

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#11]
Modify The ReadMe so that its easier for other contributors to get started with project

**Comment by sarkartanmay393** [comment]
Referred from JWoC,
Assign me this issue, I am gonna make it easy to read and elegant.

**Comment by vilgad** [comment]
> Referred from JWoC, Assign me this issue, I am gonna make it easy to read and elegant.

Hello Tanmay
Welcome to the open source community

Am sorry but we can't assign any issue before 1st feb. All the Mentees can contribute after 1st feb, before 1st feb no contribution will be counted

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC
