### ISSUE TITLE
After ViewPager Addition, Bottom navigation view's actions aren't working properly.

### ISSUE THREAD

**Issue by vivekgupta4Git** [Kajal13081/Gallery-Application#113]
Steps to reproduce bug
1) When Clicking an image in scrolling fragment  we reach to full_image_fragment ( say image1 ) which has viewpager . 
2) In ViewPager, slide left or right to see other images.
3) Click on any action of Bottom navigation view, It will display previous image (which was loaded in step i.e image1) details and perform action on it instead of new Image which is getting displayed in viewpager.

**Comment by SB2318** [comment]
I will try to work it out. Assign it to me.
