### ISSUE TITLE
Add Sort Feature

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#13]
add a sort feature to sort images on basis of their creation date, modification, size etc

**Comment by vivekgupta4Git** [comment]
By adding filter on recycler view and using material design chips will do the work.

**Comment by Kajal13081** [comment]
Hey @vivekgupta4Git sure, you can try it on your setup first. Contributions will start from 1st.

**Comment by vilgad** [comment]
hey guys,
i can understand your enthusiasm for open source contribution and thanks
for selecting our project but we will appreciate a lot if you guys can also
chat with us on the JWOC discord channel rather than on comments because
the comment section will be filled with the discussion which is not good
for others who visits the issue for JWOC ,so comment on the issue that you
wanna work on it and want us to assign it to you and if there is any doubt
related to issue or project we can easily clear it on discord. Bonding
with the mentors and other mentees are also important thats why the discord
channel is created
I hope you guys understand it

Here is the discord link JWOC Discord
<https://discord.com/invite/ve6ad4jfEP>


this is my discord id: Vilgad#0291

Happy Coding ;)

**Comment by vivekgupta4Git** [comment]
I want to work on this enhancement under JWOC.

**Comment by vivekgupta4Git** [comment]
I am up for this work!!
