### ISSUE TITLE
Hide the bottom navigation and status bar

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#15]
if user open the image and tap on the screen then bottom navigation and status bar should not display and when he/she again tap on the screen then it should display the both

**Comment by shubhanshu-coder** [comment]
i am interested in it?

**Comment by vilgad** [comment]
> i am interested in it?

We can assign issues only after 1st feb.
Till then join the JWOC discord server and bond with other mentors and mentees

**Comment by shubhanshu-coder** [comment]
can i work on this ?

**Comment by vilgad** [comment]
sure, i am assigning it to you

**Comment by vilgad** [comment]
This issue is up for grab

**Comment by binayshaw7777** [comment]
Hey @vilgad  I'm interested to work on it but before that can you please tell me about when to hide bottom navigation bar and status bar?

**Comment by Kajal13081** [comment]
> Hey @vilgad I'm interested to work on it but before that can you please tell me about when to hide bottom navigation bar and status bar?

when user opens the image and touch the screen then they should hide and when screen is touched again then both should display again.

**Comment by binayshaw7777** [comment]
Hey, I asked what what to do, why you assigned me? Sorry, please unassign.

**Comment by ken1000minus7** [comment]
Would like to work on this issue under JWOC✌️
