### ISSUE TITLE
App not working on Redmi note 7 pro

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#16]
this app is not showing images on Redmi note 7 so debug the and make the app work 

Happy Coding ;)

**Comment by vivekgupta4Git** [comment]
What kind of error ? is there any issue with permission?

**Comment by vilgad** [comment]
> What kind of error ? is there any issue with permission?

no first it ask for permission then after accepting it doesn't show images and other things

**Comment by vivekgupta4Git** [comment]
Please assign me this issue
