### ISSUE TITLE
Suggest an impressive APP ICON

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#19]

**Comment by girijakar** [comment]
<img src="https://user-images.githubusercontent.com/42700980/151744347-a46e7a5a-a51f-48f9-b762-018a46abb9d2.png" width="200">
Have a look at this one.

**Comment by vilgad** [comment]
this one is good but search for other options as well

**Comment by vilgad** [comment]
hey guys,
i can understand your enthusiasm for open source contribution and thanks
for selecting our project but we will appreciate a lot if you guys can also
chat with us on the JWOC discord channel rather than on comments because
the comment section will be filled with the discussion which is not good
for others who visits the issue for JWOC ,so comment on the issue that you
wanna work on it and want us to assign it to you and if there is any doubt
related to issue or project we can easily clear it on discord. Bonding
with the mentors and other mentees are also important thats why the discord
channel is created
I hope you guys understand it

Here is the discord link JWOC Discord
<https://discord.com/invite/ve6ad4jfEP>


this is my discord id: Vilgad#0291

Happy Coding ;)

**Comment by binayshaw7777** [comment]
Hi there, I'm interested to suggest app icon. Well, I'm a graphics designer too, so if needed I can design myself one too.
Can you please explain more about this issue?

I'm interested to work on this issue and get assigned.

**Comment by vilgad** [comment]
can you please comment on this issue actually i am unable to see your
comment on that issue in  github

**Comment by binayshaw7777** [comment]
Hey, I'm Interested to design and suggest App Icon for you!
@vilgad

**Comment by vilgad** [comment]
> Hey, I'm Interested to design and suggest App Icon for you! @vilgad
All the best

**Comment by binayshaw7777** [comment]
@vilgad  Hey, Can you tell me like what type of app logo you like or want? So that I can figure out your requirements and work on it.

**Comment by binayshaw7777** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/62587060/151993209-9cf509fe-6d12-49c2-ade4-f9c71f46ab79.png)
Does this looks okay? or shall I change the design?

**Comment by vilgad** [comment]
@binayshaw7777 please have this discussion on discord
