### ISSUE TITLE
Add favourites feature

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#21]

**Comment by vivekgupta4Git** [comment]
Can we implement this feature on longPress on image? I mean, if user long press on the image, we will notifiy user about addition of the image in favourite. May be we can animate the notification too.

**Comment by vilgad** [comment]
> Can we implement this feature on longPress on image? I mean, if user long press on the image, we will notifiy user about addition of the image in favourite. May be we can animate the notification too.

good idea but long press will also include for selection of multiple images so its slightly contradictory with that

**Comment by vivekgupta4Git** [comment]
Up for the issue under JWOC
