### ISSUE TITLE
Add a splash screen 

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#26]

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC

**Comment by GeekLord04** [comment]
I want to work on this issue under JWOC

**Comment by shubhanshu-coder** [comment]
can i work ?

**Comment by vilgad** [comment]
> can i work under jwoc ?

sorry we can assign issues only on first come first serve basis

**Comment by vilgad** [comment]
> I want to work on this issue under JWOC

check discord

**Comment by binayshaw7777** [comment]
I want to work on this issue under JWOC

**Comment by manishbajagai2** [comment]
A pull request to this issue has been made. Please check it out #40

**Comment by vilgad** [comment]
> A pull request to this issue has been made. Please check it out #40

@manishbajagai2 you should have first asked us to assign it to you, since @binayshaw7777 have commented before you am assigning it to him

**Comment by manishbajagai2** [comment]
Actually there was no comment after you commented check discord. I saw no assignee and started working . So when i completed only i saw a new comment. Still it's cool.
