### ISSUE TITLE
Remove the purple toolbar

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#61]
the purple toolbar is appearing on each and every fragment so it should appear only on folder fragment

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC

**Comment by vivekgupta4Git** [comment]
If we remove this toolbar then we wouldn't be able to use option menu on fragment.

**Comment by vilgad** [comment]
> If we remove this toolbar then we wouldn't be able to use option menu on fragment. 

Thats why I have mentioned that it should only visible on folder fragment not anywhere else
