### ISSUE TITLE
change the UI of floating navigation button

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#63]

**Comment by binayshaw7777** [comment]
Can you explain what type of change you want in the Bottom Navigation Bar? And do this issue is related to Kotlin class or only XML file?

**Comment by AKhatabdev** [comment]
Hello,

I would like to work on this, please provide more information.

Kind regards

**Comment by vilgad** [comment]
> Hello,
> 
> I would like to work on this, please provide more information.
> 
> Kind regards 

Change the colour and make it look like bottom navigation and instead of a circle try making it square you can also search online for better looking floating buttons and then after creating share the ss 😉

**Comment by binayshaw7777** [comment]
What type of changed is needed?

**Comment by aritra-tech** [comment]
I want to work on this issue under JWOC
