### ISSUE TITLE
remove the hiding status bar and navigation drawer feature from Full image fragment

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#91]

**Comment by aritra-tech** [comment]
If we remove the navigation drawer then how can the user share, delete and check the details of the image?

**Comment by vilgad** [comment]
> If we remove the navigation drawer then how can the user share, delete and check the details of the image?

no, you just have to remove the hiding feature of navigation drawer and status bar

**Comment by aritra-tech** [comment]
Ok got it
