### ISSUE TITLE
Add a feature to show the images user has marked as favourite

### ISSUE THREAD

**Issue by vilgad** [Kajal13081/Gallery-Application#98]

**Comment by harshit-070** [comment]
I want to work on this under JWOC

**Comment by vivekgupta4Git** [comment]
I guess, this is already implemented but bcoz of the grey n white color, you might have missed this. Please elaborate more about the issue.

**Comment by vilgad** [comment]
> I guess, this is already implemented but bcoz of the grey n white color, you might have missed this. Please elaborate more about the issue.

I mean that there should be a separate album where user will see his favourite marked photos

**Comment by vivekgupta4Git** [comment]
Can we implement this like filter?
There will be an option for user to see their favourite images or all images. Here we can add more filter too like show only images, show only videos etc. For this we need a toolbar at top , I guess.

**Comment by vilgad** [comment]
> Can we implement this like filter? There will be an option for user to see their favourite images or all images. Here we can add more filter too like show only images, show only videos etc. For this we need a toolbar at top , I guess.

I love the filter feature idea, you can go ahead with that
